### ISSUE TITLE
Traffic or analytics 

### ISSUE THREAD

**Issue by Amartya** [Amartya/TunePad#51]
Perhaps a table or Google Analytics ....

**Comment by Amartya** [comment]
I have been researching a few alternatives to Google Analytics, and I quite like this: [Fathom](https://usefathom.com) 
It's open source, MIT licensed, and if we host it ourselves (seems easy enough!), we don't need to pay for it.

**Comment by michael-horn** [comment]
That sounds like a really great option!  Maybe we can talk about how involved it will be to set up. We should also get the guidebook working soon if we can.

**Comment by Amartya** [comment]
#84 has the changes corresponding to this enhancement.
