### ISSUE TITLE
Updating the remix count seems to fail

### ISSUE THREAD

**Issue by Amartya** [Amartya/TunePad#76]
Datastore unit test 57: Remixing a project increases remix count by 1 in project stats seems to fail.

**Comment by Amartya** [comment]
More context, clicking the remix button for a featured project was increasing the stat/count in the backend but was throwing this error.

<img width="585" alt="screen shot 2019-02-14 at 12 57 37 am" src="https://user-images.githubusercontent.com/279301/52769041-c713cc80-2ff4-11e9-866f-93be3c7b18b4.png">

Fix was to add jsonify() in the return statement (it was earlier return _select( ....), and is now return jsonify(_select(......)).

**Comment by TIDAL-Lab** [comment]
This is weird. On my branch the method looks like this:


#--------------------------------------------------------------------------
# used to increase the remix count for a featured or shared project.
#--------------------------------------------------------------------------
@tunepad_api.route('/project_stats/<int:pid>/remix/', methods=['GET'])
def remixProject(pid):
  try:
    _update(SQL_PROJECT_STATS_INSERT.format(pid, pid))
    _update(SQL_PROJECT_STATS_REMIX.format(pid))
    return jsonify(_select(SQL_PROJECT_STATS_SELECT.format(pid)))
  except:
    abort(404)


Did the jsonify somehow get removed in a later branch? I can’t imagine why we would have done that.

**Comment by Amartya** [comment]
It was me Mike. I think while adding the showcase end-point, I must have accidentally types/deleted this line and then didn't fix it right. My apologies :(.

<img width="1222" alt="screen shot 2019-02-14 at 9 51 01 am" src="https://user-images.githubusercontent.com/279301/52798738-28ac5900-303e-11e9-8707-f4fee917e1e8.png">

It's in this commit: [Link](https://github.com/Amartya/TunePad/commit/a2074d13dcce2bd1247e8fa580af0c232f8dcc34)

**Comment by TIDAL-Lab** [comment]
no worries! glad there’s an explanation!! though this makes me think we should figure out unit testing soon.
