### ISSUE TITLE
Fix meta information for TunePad (for Google listing)

### ISSUE THREAD

**Issue by Amartya** [Amartya/TunePad#83]
![image 1](https://user-images.githubusercontent.com/279301/52921290-37fc0280-32db-11e9-96d7-0faeafaafd83.png)

**Comment by Amartya** [comment]
Based on the recommendations in this [Google Page](https://support.google.com/webmasters/answer/79812) added some meta information for TunePad. 
Note, Google automatically parses the page to create something called a "snippet". Our snippet shows EarSketch because it above-the-fold. There are two options, we can either move that to the bottom of the page, i.e. Try TunePad Button >> TunePad's features >> TunePad featured tracks >> EarSketch OR add a meta tag that says "nosnippet". This apparently "Prevents a text snippet or video preview from being shown in the search results."

**Comment by michael-horn** [comment]
If we add a meta tag description in the head, will google look at that instead? We can also talk to Tom about adding more above-the-fold text.

**Comment by Amartya** [comment]
I added the meta description tags (just sent you an email about it as well). The details of the changes are [in this commit](https://github.com/Amartya/TunePad/commit/b0a17c821c70b31236e67ef22e4fe6887b69c74f).

**Comment by Amartya** [comment]
Closing this issue, meta descriptions are now on tunepad.live. If we need to edit them, we can open another issue.
