### ISSUE TITLE
missing brew taps in readme Step 6

### ISSUE THREAD

**Issue by r-gillespie** [Amartya/TunePad#88]
Received the following error during Step 6 of installation guide:
`(tunepadEnv) dhcp-129-105-244-166:TunePad rlg532$ brew install dart --devel
Error: No available formula with the name "dart" `

Needed to add brew tap:
`brew tap dart-lang/dart`

**Comment by Amartya** [comment]
Thanks a bunch Russell. I need to update the readme quite a bit (the mongodb installation is no longer needed, we moved everything to Postgres. I'll do that tomorrow).

**Comment by Amartya** [comment]
Created a new branch called readme-fix that has the first pass of fixing this. If you are spending time on this, get the instructions from that branch.

**Comment by Amartya** [comment]
@r-gillespie, I am closing this issue for now, the new readme notes should get us going. However, once we sit down together, we can double-check it :).
