### ISSUE TITLE
Redirect ntango version to tunepad.live

### ISSUE THREAD

**Issue by Amartya** [Amartya/TunePad#94]
Google seems to be ranking the older website higher up.

<img width="806" alt="screen shot 2019-02-26 at 5 40 10 pm" src="https://user-images.githubusercontent.com/279301/53451766-96b53080-39ed-11e9-8305-35db3ced767c.png">

Redirect https://ntango.sesp.northwestern.edu/TunePad2/ to tunepad.live?

**Comment by michael-horn** [comment]
I added redirects to 

https://ntango.sesp.northwestern.edu/TunePad2

and to 

https://ntango.sesp.northwestern.edu/TunePad

**Comment by Amartya** [comment]
Sweeeeet! And Fathom picked it up too :)

<img width="365" alt="screen shot 2019-02-27 at 10 21 42 pm" src="https://user-images.githubusercontent.com/279301/53539083-25a17600-3ade-11e9-9ab1-1e3b1802e921.png">
